#!/bin/sh

#sudo su -
#wget https://raw.githubusercontent.com/yunolawliet/NVPS/master/NSimplex && chmod +x NSimplex && ./NSimplex

# initializing var
IP=$(curl -s4 http://ifconfig.me)
INTERFACE=$(ip -4 route | grep default | head -1 | cut -d' ' -f5)
PORT=1337
PROXY_PORT=1338
DNS1=1.1.1.1
DNS2=1.0.0.1
PAYLOAD="POST https://e9413.g.akamaiedge.net HTTP/1.0"

# GMT +8
ln -fs /usr/share/zoneinfo/Asia/Manila /etc/localtime

# Use Old OpenVPN
wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add -
sleep 2
echo "deb http://build.openvpn.net/debian/openvpn/release/2.4 stretch main" > /etc/apt/sources.list.d/openvpn-aptrepo.list

# Requirements
apt-get update
apt-get -y upgrade 
apt-get -y install openvpn
apt-get -y install easy-rsa
apt-get -y install privoxy
apt-get -y install ufw
apt-get -y install fail2ban
apt-get -y install iptables-persistent
apt-get -y install build-essential

#Flush any pre-existing rules
iptables -F && iptables -X

# ipv4 iptables
cat >> /etc/iptables/rules.v4 << END
*filter
# Custom
-I FORWARD -s 10.8.0.0/24 -j ACCEPT
-t nat -A POSTROUTING -o $INTERFACE -j MASQUERADE
-I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i tun+ -j ACCEPT

# Allow all loopback (lo) traffic and reject anything
# to localhost that does not originate from lo.
-A INPUT -i lo -j ACCEPT
-A INPUT ! -i lo -s 127.0.0.0/8 -j REJECT
-A OUTPUT -o lo -j ACCEPT

# Allow ping and ICMP error returns.
-A INPUT -p icmp -m state --state NEW --icmp-type 8 -j ACCEPT
-A INPUT -p icmp -m state --state ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT -p icmp -j ACCEPT

# Allow SSH.
-A INPUT -i $INTERFACE -p tcp -m state --state NEW,ESTABLISHED --dport 22 -j ACCEPT
-A OUTPUT -o $INTERFACE -p tcp -m state --state ESTABLISHED --sport 22 -j ACCEPT

# Allow UDP/TCP traffic on ports
-A INPUT -i $INTERFACE -p tcp -m state --state NEW,ESTABLISHED --dport $PORT -j ACCEPT
-A OUTPUT -o $INTERFACE -p tcp -m state --state ESTABLISHED --sport $PORT -j ACCEPT
-A INPUT -i $INTERFACE -p tcp -m state --state NEW,ESTABLISHED --dport $PROXY_PORT -j ACCEPT
-A OUTPUT -o $INTERFACE -p tcp -m state --state ESTABLISHED --sport $PROXY_PORT -j ACCEPT

# Allow DNS resolution and limited HTTP/S on $INTERFACE.
# Necessary for updating the server and timekeeping.
-A INPUT -i $INTERFACE -p udp -m state --state ESTABLISHED --sport 53 -j ACCEPT
-A OUTPUT -o $INTERFACE -p udp -m state --state NEW,ESTABLISHED --dport 53 -j ACCEPT
-A INPUT -i $INTERFACE -p tcp -m state --state ESTABLISHED --sport 80 -j ACCEPT
-A INPUT -i $INTERFACE -p tcp -m state --state ESTABLISHED --sport 443 -j ACCEPT
-A OUTPUT -o $INTERFACE -p tcp -m state --state NEW,ESTABLISHED --dport 80 -j ACCEPT
-A OUTPUT -o $INTERFACE -p tcp -m state --state NEW,ESTABLISHED --dport 443 -j ACCEPT

# Allow traffic on the TUN interface so OpenVPN can communicate with $INTERFACE.
-A INPUT -i tun0 -j ACCEPT
-A OUTPUT -o tun0 -j ACCEPT

# Log any packets which don't fit the rules above.
# (optional but useful)
-A INPUT -m limit --limit 3/min -j LOG --log-prefix "iptables_INPUT_denied: " --log-level 4
-A FORWARD -m limit --limit 3/min -j LOG --log-prefix "iptables_FORWARD_denied: " --log-level 4
-A OUTPUT -m limit --limit 3/min -j LOG --log-prefix "iptables_OUTPUT_denied: " --log-level 4

# then reject them.
-A INPUT -j REJECT
-A FORWARD -j REJECT
-A OUTPUT -j REJECT


# ANTI-TORRENT ############################
-N LOGDROP > /dev/null 2> /dev/null
-F LOGDROP
-A LOGDROP -j DROP

#Torrent
-D FORWARD -m string --algo bm --string "BitTorrent" -j LOGDROP 
-D FORWARD -m string --algo bm --string "BitTorrent protocol" -j LOGDROP
-D FORWARD -m string --algo bm --string "peer_id=" -j LOGDROP
-D FORWARD -m string --algo bm --string ".torrent" -j LOGDROP
-D FORWARD -m string --algo bm --string "announce.php?passkey=" -j LOGDROP 
-D FORWARD -m string --algo bm --string "torrent" -j LOGDROP
-D FORWARD -m string --algo bm --string "announce" -j LOGDROP
-D FORWARD -m string --algo bm --string "info_hash" -j LOGDROP

# DHT keyword
-A FORWARD -m string --string "get_peers" --algo bm -j DROP
-A FORWARD -m string --string "announce_peer" --algo bm -j LOGDROP
-A FORWARD -m string --string "find_node" --algo bm -j LOGDROP

## Modified debia commands

-A FORWARD -p udp -m string --algo bm --string "BitTorrent" -j DROP
-A FORWARD -p udp -m string --algo bm --string "BitTorrent protocol" -j DROP
-A FORWARD -p udp -m string --algo bm --string "peer_id=" -j DROP
-A FORWARD -p udp -m string --algo bm --string ".torrent" -j DROP
-A FORWARD -p udp -m string --algo bm --string "announce.php?passkey=" -j DROP 
-A FORWARD -p udp -m string --algo bm --string "torrent" -j DROP
-A FORWARD -p udp -m string --algo bm --string "announce" -j DROP
-A FORWARD -p udp -m string --algo bm --string "info_hash" -j DROP
-A FORWARD -p udp -m string --algo bm --string "tracker" -j DROP

-A INPUT -p udp -m string --algo bm --string "BitTorrent" -j DROP
-A INPUT -p udp -m string --algo bm --string "BitTorrent protocol" -j DROP
-A INPUT -p udp -m string --algo bm --string "peer_id=" -j DROP
-A INPUT -p udp -m string --algo bm --string ".torrent" -j DROP
-A INPUT -p udp -m string --algo bm --string "announce.php?passkey=" -j DROP 
-A INPUT -p udp -m string --algo bm --string "torrent" -j DROP
-A INPUT -p udp -m string --algo bm --string "announce" -j DROP
-A INPUT -p udp -m string --algo bm --string "info_hash" -j DROP
-A INPUT -p udp -m string --algo bm --string "tracker" -j DROP

-I INPUT -p udp -m string --algo bm --string "BitTorrent" -j DROP
-I INPUT -p udp -m string --algo bm --string "BitTorrent protocol" -j DROP
-I INPUT -p udp -m string --algo bm --string "peer_id=" -j DROP
-I INPUT -p udp -m string --algo bm --string ".torrent" -j DROP
-I INPUT -p udp -m string --algo bm --string "announce.php?passkey=" -j DROP 
-I INPUT -p udp -m string --algo bm --string "torrent" -j DROP
-I INPUT -p udp -m string --algo bm --string "announce" -j DROP
-I INPUT -p udp -m string --algo bm --string "info_hash" -j DROP
-I INPUT -p udp -m string --algo bm --string "tracker" -j DROP

-D INPUT -p udp -m string --algo bm --string "BitTorrent" -j DROP
-D INPUT -p udp -m string --algo bm --string "BitTorrent protocol" -j DROP
-D INPUT -p udp -m string --algo bm --string "peer_id=" -j DROP
-D INPUT -p udp -m string --algo bm --string ".torrent" -j DROP
-D INPUT -p udp -m string --algo bm --string "announce.php?passkey=" -j DROP 
-D INPUT -p udp -m string --algo bm --string "torrent" -j DROP
-D INPUT -p udp -m string --algo bm --string "announce" -j DROP
-D INPUT -p udp -m string --algo bm --string "info_hash" -j DROP
-D INPUT -p udp -m string --algo bm --string "tracker" -j DROP

-I OUTPUT -p udp -m string --algo bm --string "BitTorrent" -j DROP
-I OUTPUT -p udp -m string --algo bm --string "BitTorrent protocol" -j DROP
-I OUTPUT -p udp -m string --algo bm --string "peer_id=" -j DROP
-I OUTPUT -p udp -m string --algo bm --string ".torrent" -j DROP
-I OUTPUT -p udp -m string --algo bm --string "announce.php?passkey=" -j DROP 
-I OUTPUT -p udp -m string --algo bm --string "torrent" -j DROP
-I OUTPUT -p udp -m string --algo bm --string "announce" -j DROP
-I OUTPUT -p udp -m string --algo bm --string "info_hash" -j DROP
-I OUTPUT -p udp -m string --algo bm --string "tracker" -j DROP

## Delete

-D INPUT -m string --algo bm --string "BitTorrent" -j DROP
-D INPUT -m string --algo bm --string "BitTorrent protocol" -j DROP
-D INPUT -m string --algo bm --string "peer_id=" -j DROP
-D INPUT -m string --algo bm --string ".torrent" -j DROP
-D INPUT -m string --algo bm --string "announce.php?passkey=" -j DROP 
-D INPUT -m string --algo bm --string "torrent" -j DROP
-D INPUT -m string --algo bm --string "announce" -j DROP
-D INPUT -m string --algo bm --string "info_hash" -j DROP
-D INPUT -m string --algo bm --string "tracker" -j DROP

-D OUTPUT -m string --algo bm --string "BitTorrent" -j DROP
-D OUTPUT -m string --algo bm --string "BitTorrent protocol" -j DROP
-D OUTPUT -m string --algo bm --string "peer_id=" -j DROP
-D OUTPUT -m string --algo bm --string ".torrent" -j DROP
-D OUTPUT -m string --algo bm --string "announce.php?passkey=" -j DROP 
-D OUTPUT -m string --algo bm --string "torrent" -j DROP
-D OUTPUT -m string --algo bm --string "announce" -j DROP
-D OUTPUT -m string --algo bm --string "info_hash" -j DROP
-D OUTPUT -m string --algo bm --string "tracker" -j DROP

-D FORWARD -m string --algo bm --string "BitTorrent" -j DROP
-D FORWARD -m string --algo bm --string "BitTorrent protocol" -j DROP
-D FORWARD -m string --algo bm --string "peer_id=" -j DROP
-D FORWARD -m string --algo bm --string ".torrent" -j DROP
-D FORWARD -m string --algo bm --string "announce.php?passkey=" -j DROP 
-D FORWARD -m string --algo bm --string "torrent" -j DROP
-D FORWARD -m string --algo bm --string "announce" -j DROP
-D FORWARD -m string --algo bm --string "info_hash" -j DROP
-D FORWARD -m string --algo bm --string "tracker" -j DROP 


COMMIT
END

# Disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
cat >> /etc/iptables/rules.v6 << END
*filter
-A INPUT -j REJECT
-A FORWARD -j REJECT
-A OUTPUT -j REJECT
COMMIT
END
cat >> /etc/sysctl.d/99-sysctl.conf << END
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
END

# Refresh with the new configuration
sysctl -p

iptables-restore < /etc/iptables/rules.v4
ip6tables-restore < /etc/iptables/rules.v6

# Re-configure persistency
dpkg-reconfigure -y iptables-persistent

# OpenVPN
mkdir /etc/openvpn/easy-rsa/
cp -r /usr/share/easy-rsa/* /etc/openvpn/easy-rsa/
sed -i 's|export KEY_COUNTRY="US"|export KEY_COUNTRY="PH"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_PROVINCE="CA"|export KEY_PROVINCE="Metro Manila"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_CITY="SanFrancisco"|export KEY_CITY="Manila"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_ORG="Fort-Funston"|export KEY_ORG="SimplexVpn"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_EMAIL="me@myhost.mydomain"|export KEY_EMAIL="admin@simplexvpn.com"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_OU="MyOrganizationalUnit"|export KEY_OU="SimplexVpn"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_NAME="EasyRSA"|export KEY_NAME="SimplexVpn"|' /etc/openvpn/easy-rsa/vars
sed -i 's|export KEY_OU=changeme|export KEY_OU=SimplexVpn|' /etc/openvpn/easy-rsa/vars
cd /etc/openvpn/easy-rsa
cp openssl-1.0.0.cnf openssl.cnf
. ./vars
./clean-all
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --initca $*
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --server server
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" client
cd /etc/openvpn/easy-rsa/keys/
cp server.key server.crt ca.crt /etc/openvpn
openssl dhparam -out /etc/openvpn/dh2048.pem 2048
cd /root
wget "https://raw.githubusercontent.com/yunolawliet/VPSauto/master/tool/plugin.tgz"
tar -xzvf /root/plugin.tgz -C /usr/lib/openvpn/
chmod +x /usr/lib/openvpn/*

# Server settings
cat >> /etc/openvpn/server.conf <<-END
port $PORT
proto tcp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh2048.pem
verify-client-cert none
username-as-common-name
plugin /usr/lib/openvpn/plugins/openvpn-plugin-auth-pam.so login
server 192.168.10.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS $DNS1"
push "dhcp-option DNS $DNS2"
push "route-method exe"
push "route-delay 2"
socket-flags TCP_NODELAY
push "socket-flags TCP_NODELAY"
keepalive 10 60
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
ncp-disable
cipher none
auth none
#clients
max-clients 5000
# Speed-up
mssfix 1400
reneg-sec 0
sndbuf 0
rcvbuf 0
push "sndbuf 393216"
push "rcvbuf 393216"
tun-mtu 1400 
mssfix 1360
# Logging
status status.log
log openvpn.log
END

#Create OpenVPN Config
cat > /client.ovpn <<-END
client
dev tun
proto tcp
remote $IP $PORT
http-proxy $IP $PROXY_PORT
http-proxy-option CUSTOM-HEADER $PAYLOAD
keepalive 10 60
pull
nobind
connect-retry-max 1
connect-retry 2 300
resolv-retry 60
setenv CLIENT_CERT 0
persist-tun
auth-user-pass
comp-lzo
verb 3
cipher none
auth none
keysize 0
reneg-sec 0
ns-cert-type server
END

echo '<ca>' >> /client.ovpn
cat /etc/openvpn/ca.crt >> /client.ovpn
echo '</ca>' >> /client.ovpn

# Create custom configs
mkdir /etc/simplex/
cat > /etc/simplex/sysctl.conf <<-END
net.ipv4.ip_forward = 1
net.ipv4.conf.eth0.forwarding = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
net.ipv4.tcp_low_latency = 1
net.core.rmem_default = 524288
net.core.rmem_max = 524288
net.core.wmem_default = 524288
net.core.wmem_max = 524288
net.ipv4.tcp_wmem = 4096 87380 524288
net.ipv4.tcp_rmem = 4096 87380 524288
net.ipv4.tcp_mem = 524288 524288 524288
net.ipv4.tcp_rfc1337 = 1
net.ipv4.ip_no_pmtu_disc = 0
net.ipv4.tcp_sack = 1
net.ipv4.tcp_fack = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_ecn = 0
net.ipv4.route.flush = 1
END

# Create and Configure rc.local
cat > /etc/rc.local <<-END
#!/bin/sh -e
apt clean
rm -rf /etc/sysctl.con*
rm -rf /etc/sysctl.d/*.conf
cp /etc/simplex/sysctl.conf /etc/sysctl.conf
sysctl --system &> /dev/null
sysctl -p &> /dev/null
nameserver $DNS1 > /etc/resolv.conf
nameserver $DNS2 > /etc/resolv.conf
END

chmod +x /etc/rc.local

#PRIVOXY
cat >> /etc/privoxy/config <<-END
user-manual /usr/share/doc/privoxy/user-manual
confdir /etc/privoxy
logdir /var/log/privoxy
filterfile default.filter
logfile logfile
listen-address  0.0.0.0:$PROXY_PORT
toggle  1
enable-remote-toggle  0
enable-remote-http-toggle  0
enable-edit-actions 0
enforce-blocks 0
buffer-limit 4096
enable-proxy-authentication-forwarding 1
forwarded-connect-retries  1
accept-intercepted-requests 1
allow-cgi-request-crunching 1
split-large-forms 0
keep-alive-timeout 5
tolerate-pipelining 1
socket-timeout 300
permit-access 0.0.0.0/0 $IP
END

# UFW
ufw allow $PORT
ufw allow $PROXY_PORT
sed -i 's|DEFAULT_INPUT_POLICY="DROP"|DEFAULT_INPUT_POLICY="ACCEPT"|' /etc/default/ufw
sed -i 's|DEFAULT_FORWARD_POLICY="DROP"|DEFAULT_FORWARD_POLICY="ACCEPT"|' /etc/default/ufw

# fail2ban
cat >> /etc/fail2ban/filter.d/openvpn.local <<-END
# Fail2Ban filter for selected OpenVPN rejections
#
#

[Definition]

# Example messages (other matched messages not seen in the testing server's logs):
# Fri Sep 23 11:55:36 2016 TLS Error: incoming packet authentication failed from [AF_INET]59.90.146.160:51223
# Thu Aug 25 09:36:02 2016 117.207.115.143:58922 TLS Error: TLS handshake failed

failregex = ^ TLS Error: incoming packet authentication failed from \[AF_INET\]<HOST>:\d+$
            ^ <HOST>:\d+ Connection reset, restarting
            ^ <HOST>:\d+ TLS Auth Error
            ^ <HOST>:\d+ TLS Error: TLS handshake failed$
            ^ <HOST>:\d+ VERIFY ERROR

ignoreregex = 
END

cat >> /etc/fail2ban/jail.d/openvpn <<-END
# Fail2Ban configuration fragment for OpenVPN
[openvpn]
enabled  = true
port     = $PORT
protocol = tcp
filter   = openvpn
logpath  = /var/log/openvpn.log
maxretry = 5
END

echo "Done! Rebooting..."
reboot
